version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toy_store
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - 9000:9000
    restart: always