DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS products CASCADE;

DROP TABLE IF EXISTS product_categories CASCADE;

DROP TABLE IF EXISTS product_brands CASCADE;

DROP TABLE IF EXISTS product_orders CASCADE;

DROP TABLE IF EXISTS carts CASCADE;

DROP TABLE IF EXISTS cart_products CASCADE;

DROP TABLE IF EXISTS brands CASCADE;